version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: account_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Anirudha@123
    ports:
      - "5433:5432"
    networks:
      - shopverse-net

  eureka-server:
    build: ./Eureka-Server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - shopverse-net

  account-service:
    build: ./Account-Service
    container_name: account-service
    depends_on:
      - postgres
      - eureka-server
    ports:
      - "8081:8081"
    networks:
      - shopverse-net

  product-service:
    build: ./Product-Service
    container_name: product-service
    depends_on:
      - eureka-server
    ports:
      - "8082:8082"
    networks:
      - shopverse-net

  cart-service:
    build: ./Cart-Service
    container_name: cart-service
    depends_on:
      - eureka-server
    ports:
      - "8083:8083"
    networks:
      - shopverse-net

  order-service:
    build: ./Order-Service
    container_name: order-service
    depends_on:
      - eureka-server
    ports:
      - "8084:8084"
    networks:
      - shopverse-net

  wishlist-service:
    build: ./Wishlist-Service
    container_name: wishlist-service
    depends_on:
      - eureka-server
    ports:
      - "8085:8085"
    networks:
      - shopverse-net

  api-gateway:
    build: ./Api-Gateway
    container_name: api-gateway
    depends_on:
      - eureka-server
    ports:
      - "8080:8080"
    networks:
      - shopverse-net

networks:
  shopverse-net:
    driver: bridge
